---
- name: Postgres
  hosts: all
  become: yes
  tasks:
  #Устанавливаем vim, telnet и mc (для более удобной работы с хостами)
  - name: install base tools
    apt:
      name:
        - telnet
        - mc
      state: present
      update_cache: true

#Запуск ролей install_postgres и postgres_replication на хостах node1 и node2
- name: install postgres 15 and set up replication
  hosts: node1,node2
  gather_facts: true
  become: yes
  roles:
   - install_postgres
   - postgres_replication
  tags: replication

- name: Настройка barman
  hosts: all
  gather_facts: true
  become: yes
  roles:
   - install_barman
  tags: barman

...